#!/usr/bin/env python
# encoding: UTF-8
from enebootools.assembler import config, AssemblerInterface



iface = AssemblerInterface()

if iface.parse_args(): # parsea los argumentos de entrada de consola
    # Si el parseo no devuelve error,
    iface.execute_actions() # ejecuta las acciones detectadas.
